(()=>{"use strict";const A=window.AdminApp,$=A.qs,all=A.qsa,S=A.require();if(!S)return;A.shell("classes","إدارة الفصول");let DATA=null,GRADE=null,dirty=new Set();load();
async function load(){A.alert($("#pageMsg"),"جاري جلب الأعداد وإعدادات الفصول...","info");try{DATA=await A.api({action:"dashboard"});const gs=Object.keys(DATA.classManagement||{});GRADE=gs.includes(GRADE)?GRADE:gs[0];dirty.clear();render();A.alert($("#pageMsg"),`تم تحميل البيانات · ${DATA.generatedAt||""}`,"success")}catch(e){A.alert($("#pageMsg"),e.message,"error")}}
function kpi(t,v){return `<article class="kpi"><span>${t}</span><strong>${A.num(v)}</strong></article>`}
function render(){const gs=Object.keys(DATA.classManagement||{});$("#gradeTabs").innerHTML=gs.map(g=>`<button class="grade-tab ${g===GRADE?"active":""}" data-g="${A.esc(g)}">${A.esc(g)}</button>`).join("");all(".grade-tab").forEach(b=>b.addEventListener("click",()=>{GRADE=b.dataset.g;render()}));const g=DATA.classManagement[GRADE],cs=Object.values(g.classes);const movement=cs.filter(c=>!c.excluded&&c.delta>0).reduce((s,c)=>s+c.delta,0);$("#summary").innerHTML=kpi("طلاب الصف",g.total)+kpi("فصول متاحة للنقل",g.availableClasses)+kpi("فصول مستبعدة",g.excludedClasses)+kpi("الحركة المطلوبة",movement)+kpi("الفصول الداخلة بالموازنة",g.activeClasses);renderCards(g)}
function renderCards(g){$("#classGrid").innerHTML=Object.values(g.classes).sort((a,b)=>a.classNo-b.classNo).map(c=>`<article class="class-card ${!c.available?"closed":""} ${c.excluded?"excluded":""}" data-key="${c.key}" data-grade="${g.code}" data-class="${c.classNo}" data-rec="${c.recommendedTarget}" data-count="${c.count}">
 <div class="class-card-head"><div class="class-no">الفصل<b>${c.classNo}</b></div><div class="count-box"><strong>${A.num(c.count)}</strong><small> طالب</small></div></div>
 <div class="class-card-body">
  <div class="balance-row"><div><span>الحالي</span><b>${A.num(c.count)}</b></div><div><span>المقترح</span><b>${A.num(c.recommendedTarget)}</b></div><div><span>الهدف الفعلي</span><b class="effective">${A.num(c.target)}</b></div></div>
  <div class="switch-row"><div class="switch-copy"><b>متاح لاستقبال النقل</b><small>إيقافه يخفي الفصل من موقع الطالب</small></div><label class="switch"><input class="available" type="checkbox" ${c.available?"checked":""}><i></i></label></div>
  <div class="switch-row"><div class="switch-copy"><b>مستبعد من الموازنة</b><small>لا يدخل في احتساب الهدف التلقائي</small></div><label class="switch"><input class="excluded" type="checkbox" ${c.excluded?"checked":""}><i></i></label></div>
  <div class="field"><label>العدد المستهدف</label><input class="target" inputmode="numeric" value="${c.customTarget??""}" placeholder="تلقائي: ${c.recommendedTarget}"><small>اتركه فارغًا لاستخدام الحساب التلقائي.</small></div>
  <div class="field"><label>ملاحظة الإدارة</label><input class="note" value="${A.esc(c.note||"")}" placeholder="مثال: فصل موهوبين"></div>
 </div>
 <div class="class-card-foot"><span class="save-state">${c.updatedAt?`آخر تحديث: ${A.esc(c.updatedAt)}`:"لم يعدل"}</span><button class="btn btn-soft save-one">حفظ الفصل</button></div>
 </article>`).join("");all(".class-card").forEach(card=>{card.querySelectorAll("input").forEach(x=>x.addEventListener("input",()=>changed(card)));card.querySelector(".save-one").addEventListener("click",()=>saveCard(card));preview(card)})}
function changed(card){dirty.add(card.dataset.key);card.classList.add("dirty");card.querySelector(".save-state").textContent="تعديل غير محفوظ";preview(card)}
function preview(card){const rec=Number(card.dataset.rec),raw=card.querySelector(".target").value.trim(),target=raw===""?rec:Number(raw);card.querySelector(".effective").textContent=Number.isFinite(target)?A.num(target):"—";card.classList.toggle("closed",!card.querySelector(".available").checked);card.classList.toggle("excluded",card.querySelector(".excluded").checked)}
async function saveCard(card,silent=false){const s=A.session(),b=card.querySelector(".save-one");b.disabled=true;try{await A.api({action:"saveClassSettings",gradeCode:card.dataset.grade,classNo:card.dataset.class,available:card.querySelector(".available").checked,excluded:card.querySelector(".excluded").checked,targetCount:card.querySelector(".target").value.trim(),classNote:card.querySelector(".note").value.trim(),staffName:s.staff});dirty.delete(card.dataset.key);card.classList.remove("dirty");card.querySelector(".save-state").textContent="تم الحفظ";if(!silent)A.alert($("#pageMsg"),`تم حفظ إعداد الفصل ${card.dataset.class}. سيُطبق على استعلام الطالب التالي.`,"success");return true}catch(e){A.alert($("#pageMsg"),e.message,"error");return false}finally{b.disabled=false}}
$("#autoBtn").addEventListener("click",()=>{all(".class-card").forEach(card=>{if(card.querySelector(".excluded").checked)return;card.querySelector(".target").value=card.dataset.rec;changed(card)});A.alert($("#pageMsg"),"تم وضع الأهداف المقترحة. اضغط «حفظ جميع التعديلات» لاعتمادها.","info")});
$("#saveAllBtn").addEventListener("click",async()=>{const cards=all(".class-card").filter(c=>dirty.has(c.dataset.key));if(!cards.length){A.alert($("#pageMsg"),"لا توجد تعديلات للحفظ.","info");return}$("#saveAllBtn").disabled=true;let ok=0;for(const c of cards)if(await saveCard(c,true))ok++;$("#saveAllBtn").disabled=false;if(ok===cards.length){A.alert($("#pageMsg"),"تم حفظ جميع إعدادات الفصول بنجاح.","success");await load()}else A.alert($("#pageMsg"),`تم حفظ ${ok} من ${cards.length}.`,"error")});
})();