topbar('classes');const SESSION=requireSession();let DATA=null,GRADE=null,dirty=new Set();if(SESSION)load();
async function load(){setStatus(q('#pageStatus'),'جاري قراءة أعداد الطلاب وإعدادات الفصول...','info');try{DATA=await transApi({action:'dashboard'});const gs=Object.keys(DATA.classManagement||{});GRADE=gs.includes(GRADE)?GRADE:gs[0];dirty.clear();render();setStatus(q('#pageStatus'),`تم تحميل البيانات: ${DATA.generatedAt||''}`,'ok')}catch(e){setStatus(q('#pageStatus'),e.message,'error')}}
function render(){const gs=Object.keys(DATA.classManagement||{});q('#gradeTabs').innerHTML=gs.map(g=>`<button class="grade-tab ${g===GRADE?'active':''}" data-g="${escapeHtml(g)}">${escapeHtml(g)}</button>`).join('');qa('.grade-tab').forEach(b=>b.onclick=()=>{GRADE=b.dataset.g;render()});const g=DATA.classManagement[GRADE],cs=Object.values(g.classes);const need=cs.filter(c=>!c.excluded&&c.delta>0).reduce((s,c)=>s+c.delta,0),extra=cs.filter(c=>!c.excluded&&c.delta<0).reduce((s,c)=>s+Math.abs(c.delta),0);q('#gradeSummary').innerHTML=[['طلاب الصف',g.total],['فصول متاحة للنقل',g.availableClasses],['مستبعد من الموازنة',g.excludedClasses],['حركة مطلوبة',Math.max(need,extra)],['فصول داخلة بالموازنة',g.activeClasses]].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${arNum(x[1])}</strong></div>`).join('');renderCards(g)}
function renderCards(g){q('#classGrid').innerHTML=Object.values(g.classes).sort((a,b)=>a.classNo-b.classNo).map(c=>`<article class="class-card ${!c.available?'closed':''} ${c.excluded?'excluded':''}" data-key="${c.key}" data-grade="${g.code}" data-class="${c.classNo}" data-rec="${c.recommendedTarget}" data-count="${c.count}">
 <div class="class-title"><div><small>الفصل</small><h3>${c.classNo}</h3></div><div class="class-count">${arNum(c.count)} <small>طالب</small></div></div>
 <div class="balance-line"><div><span>الحالي</span><b>${arNum(c.count)}</b></div><div><span>المقترح</span><b>${arNum(c.recommendedTarget)}</b></div><div><span>الهدف الفعلي</span><b class="effective">${arNum(c.target)}</b></div></div>
 <div class="toggle-row"><div><b>متاح لاستقبال النقل</b><small style="display:block;color:#788d92">إيقافه يخفي الفصل من موقع الطالب</small></div><input class="available" type="checkbox" ${c.available?'checked':''}></div>
 <div class="toggle-row"><div><b>مستبعد من الموازنة</b><small style="display:block;color:#788d92">لا يدخل في حساب الهدف</small></div><input class="excluded" type="checkbox" ${c.excluded?'checked':''}></div>
 <div class="field"><label>العدد المستهدف</label><input class="target" inputmode="numeric" value="${c.customTarget??''}" placeholder="تلقائي: ${c.recommendedTarget}"><small>اتركه فارغًا للحساب التلقائي.</small></div>
 <div class="field"><label>ملاحظة الإدارة</label><input class="note" value="${escapeHtml(c.note||'')}" placeholder="مثال: فصل موهوبين"></div>
 <div style="display:flex;justify-content:space-between;align-items:center;margin-top:12px"><span class="save-state">${c.updatedAt?`آخر تحديث: ${escapeHtml(c.updatedAt)}`:'لم يعدل'}</span><button class="btn btn-light save-one">حفظ الفصل</button></div>
 </article>`).join('');
 qa('.class-card').forEach(card=>{card.querySelectorAll('input').forEach(x=>x.oninput=()=>changed(card));card.querySelector('.save-one').onclick=()=>saveCard(card)});previewAll()}
function changed(card){dirty.add(card.dataset.key);card.classList.add('dirty');card.querySelector('.save-state').textContent='تعديل غير محفوظ';preview(card)}
function previewAll(){qa('.class-card').forEach(preview)}
function preview(card){const count=Number(card.dataset.count),rec=Number(card.dataset.rec),raw=card.querySelector('.target').value.trim(),target=raw===''?rec:Number(raw);card.querySelector('.effective').textContent=Number.isFinite(target)?arNum(target):'—';card.classList.toggle('closed',!card.querySelector('.available').checked);card.classList.toggle('excluded',card.querySelector('.excluded').checked)}
async function saveCard(card,silent=false){const s=getSession(),payload={action:'saveClassSettings',gradeCode:card.dataset.grade,classNo:card.dataset.class,available:card.querySelector('.available').checked,excluded:card.querySelector('.excluded').checked,targetCount:card.querySelector('.target').value.trim(),classNote:card.querySelector('.note').value.trim(),staffName:s.staff};const b=card.querySelector('.save-one');b.disabled=true;try{await transApi(payload);dirty.delete(card.dataset.key);card.classList.remove('dirty');card.querySelector('.save-state').textContent='تم الحفظ';if(!silent)setStatus(q('#pageStatus'),`تم حفظ إعداد الفصل ${card.dataset.class}. سيظهر التغيير للطلاب في الاستعلام التالي.`,'ok');return true}catch(e){setStatus(q('#pageStatus'),e.message,'error');return false}finally{b.disabled=false}}
q('#autoTargets').onclick=()=>{qa('.class-card').forEach(card=>{if(card.querySelector('.excluded').checked)return;card.querySelector('.target').value=card.dataset.rec;changed(card)});setStatus(q('#pageStatus'),'تم وضع الأعداد المقترحة. اضغط «حفظ جميع التعديلات» لاعتمادها.','info')};
q('#saveAll').onclick=async()=>{const cards=qa('.class-card').filter(c=>dirty.has(c.dataset.key));if(!cards.length){setStatus(q('#pageStatus'),'لا توجد تعديلات للحفظ.','info');return}q('#saveAll').disabled=true;let ok=0;for(const c of cards)if(await saveCard(c,true))ok++;q('#saveAll').disabled=false;if(ok===cards.length){setStatus(q('#pageStatus'),'تم حفظ جميع إعدادات الفصول بنجاح.','ok');await load()}else setStatus(q('#pageStatus'),`تم حفظ ${ok} من ${cards.length}.`,'error')};