(()=>{"use strict";const A=window.AdminApp,$=A.qs,all=A.qsa;let DATA=null,GRADE=null,selected=null;
const login=$("#loginOverlay"),cached=A.session();if(cached.key&&cached.staff){$("#keyInput").value=cached.key;$("#staffInput").value=cached.staff;loginNow(cached.key,cached.staff)}
$("#loginForm").addEventListener("submit",e=>{e.preventDefault();loginNow($("#keyInput").value.trim(),$("#staffInput").value.trim())});
async function loginNow(key,staff){if(!key||!staff){A.alert($("#loginMsg"),"أدخل مفتاح الوصول واسم الموظف.","error");return}A.alert($("#loginMsg"),"جاري التحقق من الصلاحية...","info");try{DATA=await A.api({action:"dashboard"},key);A.saveSession(key,staff);login.classList.add("hidden");A.shell("dashboard","لوحة التحكم");render()}catch(e){A.alert($("#loginMsg"),e.message,"error")}}
$("#refreshBtn").addEventListener("click",load);
async function load(){A.alert($("#pageMsg"),"جاري تحديث البيانات...","info");try{DATA=await A.api({action:"dashboard"});render();A.alert($("#pageMsg"),`تم تحديث البيانات · ${DATA.generatedAt||""}`,"success")}catch(e){A.alert($("#pageMsg"),e.message,"error")}}
function kpi(title,value,icon){return `<article class="kpi"><div class="kpi-top"><span>${title}</span><div class="kpi-icon">${A.icon(icon)}</div></div><strong>${A.num(value)}</strong></article>`}
function render(){if(!DATA)return;const s=DATA.summary||{};$("#kpis").innerHTML=kpi("إجمالي الطلاب",s.totalStudents,"users")+kpi("طلبات النقل",s.totalRequests,"requests")+kpi("قيد المراجعة",s.pending,"clock")+kpi("مقبول",s.approved,"check")+kpi("مرفوض",s.rejected,"x");const gs=Object.keys(DATA.classManagement||{});GRADE=gs.includes(GRADE)?GRADE:gs[0];$("#gradeTabs").innerHTML=gs.map(g=>`<button class="grade-tab ${g===GRADE?"active":""}" data-grade="${A.esc(g)}">${A.esc(g)}</button>`).join("");all(".grade-tab").forEach(b=>b.addEventListener("click",()=>{GRADE=b.dataset.grade;renderBalance();all(".grade-tab").forEach(x=>x.classList.toggle("active",x===b))}));renderBalance();renderRequests()}
function renderBalance(){const g=DATA.classManagement?.[GRADE];if(!g)return;const max=Math.max(...Object.values(g.classes).map(c=>c.count),1);$("#balanceGrid").innerHTML=Object.values(g.classes).sort((a,b)=>a.classNo-b.classNo).map(c=>{const d=Number(c.delta);return `<div class="class-stat" style="${!c.available?"opacity:.58":""}"><div class="class-stat-head"><div><small>الفصل ${c.classNo}</small><strong>${A.num(c.count)}</strong></div><span class="delta ${d>0?"need":d<0?"extra":"ok"}">${c.excluded?"مستبعد":d>0?`يحتاج ${A.num(d)}`:d<0?`فائض ${A.num(Math.abs(d))}`:"متوازن"}</span></div><div class="progress"><i style="width:${Math.min(100,c.count/max*100)}%"></i></div><small>المستهدف: ${A.num(c.target)} ${!c.available?"· مغلق للنقل":""}</small></div>`}).join("")}
$("#statusFilter").addEventListener("change",renderRequests);$("#searchInput").addEventListener("input",renderRequests);
function renderRequests(){if(!DATA)return;const f=$("#statusFilter").value,t=$("#searchInput").value.trim();const rows=(DATA.requests||[]).filter(r=>(f==="الكل"||r.status===f)&&(!t||`${r.name} ${r.studentId} ${r.requestId}`.includes(t)));$("#requestsBody").innerHTML=rows.length?rows.map(r=>`<tr><td><b>${A.esc(r.requestId)}</b><br><small>${A.esc(r.date)}</small></td><td>${A.esc(r.name)}<br><small>${A.esc(r.studentId)}</small></td><td>${A.esc(r.grade)}</td><td>${A.esc(r.fromClass)} ← ${A.esc(r.toClass)}${r.suggestedClass&&r.suggestedClass!==r.toClass?`<br><small>المقترح: ${A.esc(r.suggestedClass)}</small>`:""}</td><td>${A.esc(r.reason)}</td><td><span class="badge ${A.balanceClass(r.balanceLabel)}">${A.esc(r.balanceLabel)}</span></td><td><span class="badge ${A.statusClass(r.status)}">${A.esc(r.status)}</span></td><td>${r.status==="قيد المراجعة"?`<div class="action-row"><button class="mini approve" data-id="${A.esc(r.requestId)}">اعتماد</button><button class="mini reject" data-id="${A.esc(r.requestId)}">رفض</button></div>`:`<small>${A.esc(r.approvedBy||"—")}</small>`}</td></tr>`).join(""):`<tr><td colspan="8">لا توجد طلبات مطابقة.</td></tr>`;all(".mini").forEach(b=>b.addEventListener("click",()=>openDecision(b.dataset.id,b.classList.contains("approve")?"approve":"reject")))}
function openDecision(id,decision){selected={id,decision};const r=DATA.requests.find(x=>x.requestId===id);$("#decisionTitle").textContent=decision==="approve"?"اعتماد طلب النقل":"رفض طلب النقل";$("#decisionInfo").innerHTML=`<p><b>${A.esc(r.name)}</b> · ${A.esc(r.grade)}</p><p>من الفصل <b>${A.esc(r.fromClass)}</b> إلى الفصل <b>${A.esc(r.toClass)}</b> · <span class="badge ${A.balanceClass(r.balanceLabel)}">${A.esc(r.balanceLabel)}</span></p>`;$("#decisionNote").value="";$("#decisionModal").classList.remove("hidden")}
$("#cancelDecision").addEventListener("click",()=>$("#decisionModal").classList.add("hidden"));$("#approveDecision").addEventListener("click",()=>decide("approve"));$("#rejectDecision").addEventListener("click",()=>decide("reject"));
async function decide(decision){if(!selected)return;$("#approveDecision").disabled=$("#rejectDecision").disabled=true;A.alert($("#decisionMsg"),"جاري حفظ القرار...","info");try{const s=A.session();await A.api({action:"decision",requestId:selected.id,decision,note:$("#decisionNote").value.trim(),staffName:s.staff});$("#decisionModal").classList.add("hidden");await load()}catch(e){A.alert($("#decisionMsg"),e.message,"error")}finally{$("#approveDecision").disabled=$("#rejectDecision").disabled=false}}
})();