(()=>{"use strict";const A=window.AdminApp,$=A.qs,S=A.require();if(!S)return;A.shell("report","التقرير النهائي");$("#preparedBy").textContent=S.staff;$("#signName").textContent=S.staff;let DATA=null;load();
$("#refreshBtn").addEventListener("click",load);$("#printBtn").addEventListener("click",()=>window.print());
async function load(){A.alert($("#reportMsg"),"جاري إعداد التقرير من البيانات الحالية...","info");try{DATA=await A.api({action:"dashboard"});render();A.alert($("#reportMsg"),"تم تحديث التقرير بنجاح.","success")}catch(e){A.alert($("#reportMsg"),e.message,"error")}}
function kpi(t,v){return `<article class="kpi"><span>${t}</span><strong>${A.num(v)}</strong></article>`}
function render(){const s=DATA.summary||{};$("#generatedAt").textContent=DATA.generatedAt||new Date().toLocaleString("ar-SA");$("#reportKpis").innerHTML=kpi("إجمالي الطلاب",s.totalStudents)+kpi("طلبات النقل",s.totalRequests)+kpi("قيد المراجعة",s.pending)+kpi("مقبول",s.approved)+kpi("مرفوض",s.rejected);
$("#classReports").innerHTML=Object.entries(DATA.classManagement||{}).map(([grade,g])=>`<div class="report-grade"><div class="report-grade-title">${A.esc(grade)} · ${A.num(g.total)} طالب</div><div class="table-wrap"><table class="table" style="min-width:720px"><thead><tr><th>الفصل</th><th>الحالي</th><th>المقترح</th><th>المستهدف</th><th>الاحتياج / الفائض</th><th>استقبال النقل</th><th>الموازنة</th><th>ملاحظة</th></tr></thead><tbody>${Object.values(g.classes).sort((a,b)=>a.classNo-b.classNo).map(c=>`<tr><td>${c.classNo}</td><td>${A.num(c.count)}</td><td>${A.num(c.recommendedTarget)}</td><td>${A.num(c.target)}</td><td>${c.delta>0?`يحتاج ${A.num(c.delta)}`:c.delta<0?`فائض ${A.num(Math.abs(c.delta))}`:"متوازن"}</td><td>${c.available?"متاح":"مغلق"}</td><td>${c.excluded?"مستبعد":"داخل"}</td><td>${A.esc(c.note||"—")}</td></tr>`).join("")}</tbody></table></div></div>`).join("");
renderPlan();const rows=DATA.requests||[];$("#reportRows").innerHTML=rows.length?rows.map(r=>`<tr><td>${A.esc(r.requestId)}</td><td>${A.esc(r.name)}<br><small>${A.esc(r.studentId)}</small></td><td>${A.esc(r.grade)}</td><td>${A.esc(r.fromClass)} ← ${A.esc(r.toClass)}</td><td>${A.esc(r.reason)}</td><td>${A.esc(r.balanceLabel)}</td><td>${A.esc(r.status)}</td><td>${A.esc(r.decisionDate||"—")}</td><td>${A.esc(r.approvedBy||"—")}</td></tr>`).join(""):`<tr><td colspan="9">لا توجد طلبات مسجلة.</td></tr>`}
function renderPlan(){const plan=[];for(const [grade,g] of Object.entries(DATA.classManagement||{})){let donors=Object.values(g.classes).filter(c=>!c.excluded&&c.count>c.target).map(c=>({c:c.classNo,n:c.count-c.target})),needs=Object.values(g.classes).filter(c=>!c.excluded&&c.available&&c.count<c.target).map(c=>({c:c.classNo,n:c.target-c.count}));let i=0,j=0;while(i<donors.length&&j<needs.length){const n=Math.min(donors[i].n,needs[j].n);if(n>0)plan.push({grade,from:donors[i].c,to:needs[j].c,n});donors[i].n-=n;needs[j].n-=n;if(!donors[i].n)i++;if(!needs[j].n)j++}}$("#planList").innerHTML=plan.length?plan.map(x=>`<div class="plan-item"><b>${A.esc(x.grade)}</b> · نقل تقريبي لعدد <b>${A.num(x.n)}</b> طالب من الفصل <b>${x.from}</b> إلى الفصل <b>${x.to}</b></div>`).join(""):`<div class="plan-item">لا توجد حركة إضافية مطلوبة وفق الأهداف الحالية.</div>`}
$("#csvBtn").addEventListener("click",()=>{if(!DATA)return;const rows=[["رقم الطلب","رقم الطالب","اسم الطالب","الصف","الفصل الحالي","الفصل المطلوب","السبب","الحالة","تقييم الموازنة","ملاحظة الإدارة","تاريخ القرار","اعتمد بواسطة"],...(DATA.requests||[]).map(r=>[r.requestId,r.studentId,r.name,r.grade,r.fromClass,r.toClass,r.reason,r.status,r.balanceLabel,r.managementNote,r.decisionDate,r.approvedBy])];const csv="\ufeff"+rows.map(row=>row.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="student-transfer-final-report.csv";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
})();